export default {
  baseUrl: "/api/v1",
  article: "/article",
  articles: "/articles",
  tags: "/tags",
  tag: "/tag",
  categories: "/categories",
  category: "/category",
  info: "/info",
  timeline: "/timeline",
  messages: "/messages",
  quiz: "/quiz",
  quiz1: "/quizpaper/quiz1",
  order: '/orderForm',
  orderCheck: '/order/check',
  doctorlist: "/order/doctorlist",
  doctorCalendar: "/doctorOrder",
  doctordate: "/order/doctordate",
}
