spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://139.155.69.60:3306/psychology?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 102@uestc

  redis:
    host: 127.0.0.1
    port: 6379
logging:
  level:
    pers.qianyucc.qblog.dao: trace

minio:
  server: http://117.50.23.198:8884/
  access-key: AKIAIOSFODNN7EXAMPLE
  secret-key: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
  bucket: qblog
qiniu:
  server: http://upload-z2.qiniup.com
  url: http://images.codingli.xyz/
  access-key: knQrQNZO7UAIGCmDuXpSt_yeeF2WI_OykM6IITNN
  secret-key: DYr3LHywS5TdxPuxvcuBsW_3JkfOBnvEkau5Ubvn
  bucket: qimages-api

setting:
  path: _qblog/qblog.setting
remote:
  logUrl: http://localhost:7004/
